-- Seed: 4 ekstra turer (Vietnam Northern Loop + 3 varierte)
-- Kjør etter seed_tours.sql. Alt inkludert-pakker og lengre beskrivelser.

insert into public.tours (
  title,
  short_description,
  long_description,
  sted,
  vanskelighetsgrad,
  sesong,
  terreng,
  price,
  start_date,
  end_date,
  seats_available,
  total_seats,
  image_url,
  status,
  hoydepunkter
) values
  (
    'Vietnam Northern Loop',
    'For mange eventyrere er Nord-Vietnam et fantastisk land med ubeskrivelige naturopplevelser og kulturelle inntrykk. Bli med på motorsykkeltur i de nordlige fjellområdene – opplevelser for livet. Alt inkludert.',
    'For mange eventyrere er Nord-Vietnam et fantastisk land med masse ubeskrivelig naturopplevelser og kulturelle inntrykk. Derfor er det å bli med på motorsykkeltur i Nord-Vietnam en opplevelse for livet. Man åpner opp sinnet og utfordrer seg selv. Dette fantastiske landet er hjemmet til mange etniske minoriteter og vi blir nærmere kjent med flere av dem. Vietnam byr på et rikt kulturliv og kulturelle opplevelser. På denne turen, i de nordlige fjellområdet av Vietnam kommer du nært på opplevelser som gir deg et uforglemmelige øyeblikk og opplevelser for livet. Pakken er alt inkludert: motorsykkel, overnatting, måltider, lokal guide og innkjøring.',
    'Nord-Vietnam',
    'intermediær',
    'vinter',
    'blandet',
    22900.00,
    '2026-11-07 09:00:00+01',
    '2026-11-18 16:00:00+01',
    10,
    10,
    null,
    'published',
    E'Hanoi og innkjøring\nHa Giang og fjellpass\nEtniske landsbyer\nSapa-regionen\nMotorbåt på Halong\nLokal mat og kultur'
  ),
  (
    'Patagonia Explorer',
    'Fra Andes til ørken og isbreer. Denne ekspedisjonen tar deg gjennom Chile og Argentina med spektakulære veier, guanacoer og uendelige sletter. For deg som vil kjøre langt og oppleve det sørlige Amerika på to hjul.',
    'Patagonia Explorer er en omfattende motorsykkeltur gjennom det sørlige Sør-Amerika. Vi starter i Bariloche og følger Ruta 40 gjennom Argentina, krysser over til Chile og Torres del Paine, og returnerer via El Chaltén og Perito Moreno-breen. Turen byr på variert terreng: asfalt på hovedveier, grus og stein på avstikkere til utkikkspunkter og nasjonalparker. Overnatting skjer i små hoteller og lodges med lokal karakter. Dette er en tur for deg som har kjørt lengre turer før og er vant til lange dager i salen. Vær og vind kan være utfordrende – turen er planlagt for den beste sesongen (november–mars). Alt inkludert: motorsykkelleie, overnatting, frokost og middag, guide, supportbil for bagasje.',
    'Patagonia (Chile og Argentina)',
    'erfaren',
    'sommer',
    'blandet',
    34900.00,
    '2027-01-12 08:00:00-03',
    '2027-01-26 18:00:00-03',
    8,
    8,
    null,
    'published',
    E'Bariloche og Nahuel Huapi\nRuta 40 gjennom Patagonia\nTorres del Paine\nPerito Moreno-breen\nEl Chaltén og Fitz Roy\nØrkenlandskaper og guanacoer'
  ),
  (
    'Island – Ring Road',
    'Rundt Island på Riksvei 1: vulkaner, fossar, svart sand og geysirer. Rolig tempo med god tid til å stoppe og nyte. Passer for nybegynnere som vil oppleve Island på motorsykkel.',
    'Island Ring Road er den klassiske rundturen på Riksvei 1. Vi kjører mot klokken fra Reykjavík og besøker Gullfoss, Geysir, Jökulsárlón, Myvatn, Húsavík og Snæfellsnes. Veiene er stort sett asfalterte og i god stand, med noen korte grusstrekk. Turen er lagt opp med moderate kjøredager slik at vi får tid til å stoppe ved fossar, varme kilder og fuglefjell. Overnatting på hotell og gjestegårder. Vær på Island kan skifte fort – vi har fleksible dager og guider med god lokal kunnskap. Inkludert: motorsykkel (eget valg av modell), overnatting med frokost, guide, ferjer og innganger til attraksjoner. Egenbetaling: lunsj og middag.',
    'Island',
    'nybegynner',
    'sommer',
    'asfalt',
    28900.00,
    '2026-07-20 10:00:00+00',
    '2026-08-01 14:00:00+00',
    12,
    12,
    null,
    'published',
    E'Reykjavík start og slutt\nGullfoss og Geysir\nJökulsárlón og diamantstranden\nMyvatn og naturbad\nHúsavík og hvalsafari (valgfritt)\nSnæfellsnes halvøy'
  ),
  (
    'Atlas og ørken – Marokko',
    'Fra Marrakech over Atlasfjellene til ørkenen og tilbake. Blandet terreng, sterke farger og gode opplevelser rundt bål og berbisk kultur. For deg som vil ha litt utfordring og mye atmosfære.',
    'Denne turen tar deg fra Marrakech over Høye Atlas via Tizi n''Tichka-passet, ned til Ait Ben Haddou og videre mot ørkenen ved Merzouga. Vi overnatter i kasbah-er og ørkenleir med stjernehimmel og berbisk underholdning. På vei tilbake kan vi ta avstikkere til Todra-kløfta og Dades-dalen. Terrenget er en blanding av asfalt på nasjonale veier og grus og stein på ørkenstier og fjelloverganger. Du bør ha erfaring med grus og litt teknisk kjøring. Sesongen er valgt for behagelig varme om dagen og kjølige kvelder. Pakken inkluderer motorsykkel, overnatting (hotell og leir), alle måltider under ørkenopphold, guide og support. Visum ikke inkludert.',
    'Marokko (Atlas og Sahara)',
    'erfaren',
    'sommer',
    'blandet',
    26900.00,
    '2026-10-03 08:00:00+01',
    '2026-10-14 17:00:00+01',
    10,
    10,
    null,
    'published',
    E'Marrakech og Medina\nTizi n''Tichka-passet\nAit Ben Haddou\nØrkenleir ved Merzouga\nTodra-kløfta\nDades-dalen'
  );
